import streamlit as st
import os
import google.generativeai as genai
from dotenv import load_dotenv

# Configuración de página
st.set_page_config(
    page_title="Ava - AgentCoachAI Copywriter",
    page_icon="🏡",
    layout="centered"
)

# Cargar variables de entorno si existen (para desarrollo local)
load_dotenv()

# --- CONFIGURACIÓN SIDEBAR Y API ---
with st.sidebar:
    st.header("⚙️ Configuration / Configuración")
    
    # Opción para ingresar la API Key manualmente o usar Secrets
    api_key = st.text_input("Google Gemini API Key", type="password")
    
    # Si no hay input manual, intenta buscar en st.secrets o variables de entorno
    if not api_key:
        if "GOOGLE_API_KEY" in st.secrets:
            api_key = st.secrets["GOOGLE_API_KEY"]
        elif os.getenv("GOOGLE_API_KEY"):
            api_key = os.getenv("GOOGLE_API_KEY")

    st.markdown("---")
    st.markdown("### About Ava")
    st.info(
        "Ava is a senior real-estate copywriter designed to create persuasive, "
        "Fair-Housing-compliant listings.\n\n"
        "Ava es una redactora experta en bienes raíces diseñada para crear listados "
        "persuasivos y que cumplen con las leyes de vivienda justa."
    )

# --- DEFINICIÓN DEL ROL (SYSTEM PROMPT) ---
def get_ava_prompt(user_inputs, language):
    return f"""
    You are **Ava**, a senior real-estate copywriter created by **AgentCoachAI**.
    You write persuasive, cinematic, and Fair-Housing-compliant property descriptions.

    ====================
    YOUR OBJECTIVE
    ====================
    Turn the provided raw details into market-ready stories that help buyers visualize the home.
    
    ====================
    CRITICAL INSTRUCTION: LANGUAGE
    ====================
    YOU MUST WRITE THE OUTPUT IN: **{language.upper()}**.
    If the language is Spanish, translate the tone and style culturally, do not just translate literally.
    
    ====================
    OUTPUT FORMAT
    ====================
    Produce three unique versions:
    1. **Cinematic / Luxury Version** (400–600 words): Vivid, sensory details, storytelling structure.
    2. **Professional / Neutral Version** (300–450 words): MLS-ready, factual, elegant, focuses on features and proximity.
    3. **Short Summary Version** (120–200 words): Concise teaser, best 3-4 selling points.

    ====================
    COPYWRITING STYLE GUIDELINES
    ====================
    • Write like a professional listing agent trained by top copywriters.
    • Highlight tangible details (lifestyle imagery).
    • Mention proximity elements naturally.
    • Stay factual but inspiring.
    • COMPLIANCE: Avoid Fair-Housing violations. Describe the property, not the people.

    ====================
    QUALITY RULES
    ====================
    • Each version must be unique in rhythm.
    • Always end with: "Description generated by Ava — AgentCoachAI. FH-Compliant."

    ====================
    PROPERTY DETAILS PROVIDED BY USER
    ====================
    {user_inputs}
    """

# --- INTERFAZ PRINCIPAL ---
st.title("🏡 Ava: Real Estate AI Copywriter")
st.subheader("Generate listing descriptions that sell / Genera descripciones que venden")

# Selector de idioma de salida
output_language = st.selectbox(
    "Select Output Language / Selecciona el idioma de salida",
    ("English", "Spanish")
)

with st.form("listing_form"):
    col1, col2 = st.columns(2)
    
    with col1:
        address = st.text_input("Property Address / Dirección de la Propiedad")
        home_type = st.text_input("Home Type (e.g., Condo, Colonial) / Tipo de Propiedad")
        sqft = st.text_input("SqFt & Layout / Pies Cuadrados y Distribución", placeholder="e.g. 2000 sqft, 3 Bed, 2 Bath")
    
    with col2:
        neighborhood = st.text_area("Neighborhood Highlights / Detalles del Vecindario", height=100, 
                                    placeholder="Parks, schools, shops, commuting...")
        
    features = st.text_area("Key Features & Upgrades / Características Clave y Mejoras", height=150,
                            placeholder="Renovated kitchen, hardwood floors, new roof, pool, view...")
    
    agent_info = st.text_input("Agent Name & Contact (Optional) / Nombre y Contacto (Opcional)")

    submit_button = st.form_submit_button("✨ Generate Descriptions / Generar Descripciones")

# --- LÓGICA DE GENERACIÓN ---
if submit_button:
    if not api_key:
        st.error("❌ Please provide a Google Gemini API Key in the sidebar.")
        st.stop()

    if not address or not features:
        st.warning("⚠️ Please provide at least the Address and Key Features.")
        st.stop()

    # Configurar el modelo
    try:
        genai.configure(api_key=api_key)
        # Usamos gemini-1.5-flash por ser rápido y eficiente para texto, 
        # puedes cambiarlo a gemini-1.5-pro si quieres más creatividad.
        model = genai.GenerativeModel('gemini-1.5-flash') 
        
        # Construir los datos del usuario
        user_data_compiled = f"""
        Address: {address}
        Type: {home_type}
        Specs: {sqft}
        Neighborhood: {neighborhood}
        Key Features: {features}
        Agent Info: {agent_info}
        """

        # Crear el prompt completo
        full_prompt = get_ava_prompt(user_data_compiled, output_language)

        with st.spinner("Ava is writing your descriptions... / Ava está escribiendo..."):
            response = model.generate_content(full_prompt)
            generated_text = response.text

        # Mostrar resultados
        st.success("✅ Descriptions Generated! / ¡Descripciones Generadas!")
        st.markdown("---")
        st.markdown(generated_text)
        
        # Botón de descarga (simple text download)
        st.download_button(
            label="💾 Download Descriptions (.txt)",
            data=generated_text,
            file_name=f"listing_{address.replace(' ', '_')}.txt",
            mime="text/plain"
        )

    except Exception as e:
        st.error(f"An error occurred: {e}")
