import os
import google.generativeai as genai
from flask import Flask, request, render_template_string
from dotenv import load_dotenv

# --- CONFIGURATION ---
load_dotenv()
app = Flask(__name__)

# Configure Gemini API
# Railway will look for GOOGLE_API_KEY in the "Variables" tab
api_key = os.environ.get("GOOGLE_API_KEY")

if api_key:
    genai.configure(api_key=api_key)

# --- AVA'S SYSTEM PROMPT (English Only) ---
def get_ava_prompt(user_inputs):
    return f"""
    You are **Ava**, a senior real-estate copywriter created by **AgentCoachAI**.
    You write persuasive, cinematic, and Fair-Housing-compliant property descriptions.

    ====================
    YOUR OBJECTIVE
    ====================
    Turn the provided raw details into market-ready stories that help buyers visualize the home, 
    the setting, and the convenience of living there.

    ====================
    CRITICAL INSTRUCTION
    ====================
    **OUTPUT LANGUAGE:** ENGLISH ONLY. 
    Do not use any other language.
    
    ====================
    OUTPUT FORMAT
    ====================
    Produce three unique versions:
    1. **Cinematic / Luxury Version** (400–600 words): Vivid, sensory details, storytelling structure.
    2. **Professional / Neutral Version** (300–450 words): MLS-ready, factual, elegant.
    3. **Short Summary Version** (120–200 words): Concise teaser, best 3-4 selling points.

    ====================
    COPYWRITING STYLE GUIDELINES
    ====================
    • Write like a professional listing agent trained by top copywriters.
    • Highlight tangible details (lifestyle imagery).
    • Mention proximity elements naturally.
    • Stay factual but inspiring.
    • COMPLIANCE: Avoid Fair-Housing violations. Describe the property, not the people.

    ====================
    QUALITY RULES
    ====================
    • Each version must be unique in rhythm.
    • Always end with: "Description generated by Ava — AgentCoachAI. FH-Compliant."

    ====================
    PROPERTY DETAILS
    ====================
    {user_inputs}
    """

# --- FRONTEND (HTML/CSS - English Only) ---
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ava - Real Estate Copywriter</title>
    <style>
        body { font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f4f6f8; color: #333; margin: 0; padding: 20px; }
        .container { max-width: 800px; margin: 0 auto; background: white; padding: 40px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); }
        h1 { color: #1a202c; text-align: center; margin-bottom: 5px; }
        .subtitle { text-align: center; color: #718096; margin-bottom: 30px; font-size: 0.95em; }
        
        .form-group { margin-bottom: 20px; }
        label { display: block; margin-bottom: 8px; font-weight: 600; color: #4a5568; }
        input[type="text"], textarea { width: 100%; padding: 12px; border: 1px solid #e2e8f0; border-radius: 6px; box-sizing: border-box; font-size: 15px; }
        input[type="text"]:focus, textarea:focus { border-color: #3182ce; outline: none; ring: 2px solid #ebf8ff; }
        textarea { resize: vertical; min-height: 120px; }
        
        button { background-color: #3182ce; color: white; padding: 14px 24px; border: none; border-radius: 6px; cursor: pointer; width: 100%; font-size: 16px; font-weight: 600; transition: background 0.2s; margin-top: 10px; }
        button:hover { background-color: #2b6cb0; }
        
        .result-box { background: #f7fafc; padding: 30px; border-radius: 8px; margin-top: 40px; border: 1px solid #e2e8f0; }
        .result-content { white-space: pre-wrap; line-height: 1.7; font-family: 'Georgia', serif; color: #2d3748; }
        
        .error { color: #e53e3e; background: #fff5f5; padding: 10px; border-radius: 6px; margin-top: 20px; text-align: center; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🏡 Ava: Real Estate AI</h1>
        <p class="subtitle">AgentCoachAI Copywriter (English)</p>
        
        <form method="POST" action="/">
            <div class="form-group">
                <label>Property Address</label>
                <input type="text" name="address" placeholder="e.g. 123 Maple Ave, Beverly Hills" required>
            </div>
            
            <div class="form-group">
                <label>Home Type / Style</label>
                <input type="text" name="home_type" placeholder="e.g. Colonial, Condo, Modern Farmhouse">
            </div>
            
            <div class="form-group">
                <label>Specs (Beds, Baths, SqFt)</label>
                <input type="text" name="specs" placeholder="e.g. 4 Beds, 3 Baths, 2,800 SqFt" required>
            </div>
            
            <div class="form-group">
                <label>Neighborhood Highlights</label>
                <textarea name="neighborhood" placeholder="e.g. Great school district, walking distance to parks, quiet cul-de-sac..."></textarea>
            </div>
            
            <div class="form-group">
                <label>Key Features & Upgrades</label>
                <textarea name="features" placeholder="e.g. Renovated chef's kitchen, quartz island, hardwood floors,